name: Test SSH Connection
on:
  workflow_dispatch:
jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connection Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "SSH 연결 성공!"
            whoami
            pwd
