name: CD  
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 - Step 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "===== 단계 1: 프로세스 정리 ====="
            # 현재 실행 중인 프로세스 확인
            ps aux | grep 'java\|npm'
            # 기존 프로세스 정리 (조심스럽게 진행)
            pkill -f 'java -jar' || echo "자바 프로세스가 실행 중이지 않습니다"
            pkill -f 'npm start' || echo "npm 프로세스가 실행 중이지 않습니다"
            echo "프로세스 정리 완료"
